on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    env:
      DATABRICKS_HOST: '${{ vars.DATABRICKS_HOST }}'
      ARM_CLIENT_ID: '${{ vars.AZURE_CLIENT_ID }}'
      ARM_TENANT_ID: '${{ vars.AZURE_TENANT_ID }}'
      # DATABRICKS_ACCOUNT_ID: '9b640230-5171-41ad-8787-76b533b6bf26'
      ARM_CLIENT_SECRET: '${{ vars.AZURE_CLIENT_SECRET }}'


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Databricks CLI Setup
        uses: databricks/setup-cli@main

      - name: debug
        run: |
          echo ${DATABRICKS_HOST}
          echo ${ARM_CLIENT_ID}
          echo ${ARM_TENANT_ID}

      - name: Databricks Bundle Deploy
        run: databricks bundle deploy
