on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    env:
      DATABRICKS_HOST: '${{ vars.DATABRICKS_HOST }}'
      DATABRICKS_CLIENT_ID: '${{ vars.AZURE_CLIENT_ID }}'
      DATABRICKS_ACCOUNT_ID: '9b640230-5171-41ad-8787-76b533b6bf26'
      DATABRICKS_CLIENT_SECRET: '${{ vars.AZURE_CLIENT_SECRET }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Databricks CLI Setup
        uses: databricks/setup-cli@main

      - name: Databricks Bundle Deploy
        run: databricks bundle deploy
