on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    env:
      DATABRICKS_HOST: '${{ vars.DATABRICKS_HOST }}'
      ARM_CLIENT_ID: '${{ vars.AZURE_CLIENT_ID }}'
      ARM_TENANT_ID: '${{ vars.AZURE_TENANT_ID }}'
      ARM_CLIENT_SECRET: '${{ vars.AZURE_CLIENT_SECRET }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Databricks CLI Setup
        uses: databricks/setup-cli@main

      - name: Databricks Bundle Deploy
        run: databricks bundle deploy -t dev
